# Generated by Django 3.2.16 on 2022-12-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prdouct',
            name='image',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
